# Generated by Django 6.0.3 on 2026-03-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_sessionseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionseat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.session'),
        ),
    ]
