# Generated by Django 6.0.3 on 2026-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sessionseat_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionseat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessionseat',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sessionseat',
            constraint=models.UniqueConstraint(fields=('session', 'seat'), name='unique_session_seat', violation_error_message='This session already have this seat.'),
        ),
    ]
