# Generated by Django 6.0.3 on 2026-03-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sessionseat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='session',
        ),
    ]
